[ $theme_name = default ] && theme_name=${string_default}${string_themepack}
[ $theme_name = coloros12 ] && theme_name=${string_ColorOS12}${string_themepack}
[ $theme_name = explore ] && theme_name=${string_explore}${string_themepack}
[ $theme_name = flyme9 ] && theme_name=${string_Flyme9}${string_themepack}
[ $theme_name = lrone ] && theme_name=${string_lrone}${string_themepack}
[ $theme_name = luck7 ] && theme_name=${string_luck7}${string_themepack}
[ $theme_name = perfectcurve ] && theme_name=${string_perfectcurve}${string_themepack}
[ $theme_name = Aquamarine ] && theme_name=${string_HarmonyOSAquamarine}${string_themepack}
[ $theme_name = AmethystLake ] && theme_name=${string_EMUIAmethystLake}${string_themepack}
[ $theme_name = GoldenBeach ] && theme_name=${string_EMUIGoldenBeach}${string_themepack}
[ $theme_name = LightWings ] && theme_name=${string_EMUILightWings}${string_themepack}
[ $theme_name = Nebulae ] && theme_name=${string_EMUINebulae}${string_themepack}
[ $theme_name = StarrySky ] && theme_name=${string_EMUIStarrySky}${string_themepack}
[ $theme_name = Reconstruction ] && theme_name=${string_EMUIReconstruction}${string_themepack}
[ $theme_name = iOS ] && theme_name=${string_iOS}${string_themepack}
[ $theme_name = coloros13 ] && theme_name=ColorOS13${string_themepack}