source theme_files/hwt_theme_config
[ $sel_theme = Aquamarine ] && echo "当前选择：润泽"
[ $sel_theme = PoeticRomance ] && echo "当前选择：镜中诗"
[ $sel_theme = BlushGold ] && echo "当前选择：8号色 "
[ $sel_theme = ClearBlue ] && echo "当前选择：晴光蓝 "
[ $sel_theme = CrushGreen ] && echo "当前选择：艾草青 "
[ $sel_theme = PurpleAmber ] && echo "当前选择：紫烟琥珀 "
[ $sel_theme = AmethystLake ] && echo "当前选择：紫晶湖"
[ $sel_theme = GoldenBeach ] && echo "当前选择：碧海金沙"
[ $sel_theme = LightWings ] && echo "当前选择：光之翼"
[ $sel_theme = Nebulae ] && echo "当前选择：宇宙之眼"
[ $sel_theme = StarrySky ] && echo "当前选择：星夜彩绘"
[ $sel_theme = Reconstruction ] && echo "当前选择：未来之翼"
[ $sel_theme = Flyme9 ] && echo "当前选择：Flyme9"
[ $sel_theme = ColorOS12 ] && echo "当前选择：ColorOS12"