source theme_files/hwt_theme_config
[ $sel_theme = Aquamarine ] && echo "'@string:string_nowselected'@string:string_Aquamarine'"
[ $sel_theme = PoeticRomance ] && echo "'@string:string_nowselected'@string:string_PoeticRomance'"
[ $sel_theme = BlushGold ] && echo "'@string:string_nowselected'@string:string_BlushGold'"
[ $sel_theme = ClearBlue ] && echo "'@string:string_nowselected'@string:string_ClearBlue'"
[ $sel_theme = CrushGreen ] && echo "'@string:string_nowselected'@string:string_CrushGreen'"
[ $sel_theme = PurpleAmber ] && echo "'@string:string_nowselected'@string:string_PurpleAmber'"
[ $sel_theme = AmethystLake ] && echo "'@string:string_nowselected'@string:string_AmethystLake'"
[ $sel_theme = GoldenBeach ] && echo "'@string:string_nowselected'@string:string_GoldenBeach'"
[ $sel_theme = LightWings ] && echo "'@string:string_nowselected'@string:string_LightWings'"
[ $sel_theme = Nebulae ] && echo "'@string:string_nowselected'@string:string_Nebulae'"
[ $sel_theme = StarrySky ] && echo "'@string:string_nowselected'@string:string_StarrySky'"
[ $sel_theme = Reconstruction ] && echo "'@string:string_nowselected'@string:string_Reconstruction'"
[ $sel_theme = Flyme9 ] && echo "'@string:string_nowselected'@string:string_Flyme9'"
[ $sel_theme = ColorOS12 ] && echo "'@string:string_nowselected'@string:string_ColorOS12'"
[ $sel_theme = Firmament ] && echo "'@string:string_nowselected'@string:string_Firmament'"
[ $sel_theme = MIUI ] && echo "'@string:string_nowselected'@string:string_MIUI'"