source theme_files/theme_config
[ $sel_theme = default ] && echo "'@string:string_nowselected''@string:string_default'"
[ $sel_theme = coloros12 ] && echo "'@string:string_nowselected''@string:string_ColorOS12'"
[ $sel_theme = explore ] && echo "'@string:string_nowselected''@string:string_explore'"
[ $sel_theme = flyme9 ] && echo "'@string:string_nowselected''@string:string_Flyme9'"
[ $sel_theme = lrone ] && echo "'@string:string_nowselected''@string:string_lrone'"
[ $sel_theme = luck7 ] && echo "'@string:string_nowselected''@string:string_luck7'"
[ $sel_theme = perfectcurve ] && echo "'@string:string_nowselected''@string:string_perfectcurve'"
[ $sel_theme = Aquamarine ] && echo "'@string:string_nowselected''@string:string_HarmonyOSAquamarine'"
[ $sel_theme = AmethystLake ] && echo "'@string:string_nowselected''@string:string_EMUIAmethystLake'"
[ $sel_theme = GoldenBeach ] && echo "'@string:string_nowselected''@string:string_EMUIGoldenBeach'"
[ $sel_theme = LightWings ] && echo "'@string:string_nowselected''@string:string_EMUILightWings'"
[ $sel_theme = Nebulae ] && echo "'@string:string_nowselected''@string:string_EMUINebulae'"
[ $sel_theme = StarrySky ] && echo "'@string:string_nowselected''@string:string_EMUIStarrySky'"
[ $sel_theme = Reconstruction ] && echo "'@string:string_nowselected''@string:string_EMUIReconstruction'"